import { Product } from '@/lib/types/product'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Madhubani Fish Pair',
    price: 1200,
    description: 'A vibrant Madhubani painting of fish pair, hand-painted on handmade paper with natural colours. A timeless motif from Bihar.',
    status: 'in-stock',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/ai-market-asst-1.firebasestorage.app/o/dataset%2Fmadhubani%2Fmadhubani0.jpg?alt=media&token=770c03a1-9df2-43a8-a9c7-addb89ca132a',
    ],
    artisan: {
      name: 'Sunita Devi',
      location: 'Madhubani, Bihar',
      avatar: '',
    },
    category: 'Madhubani',
    rating: 4.9,
    relatedProducts: ['2', '3'],
  },
  {
    id: '2',
    name: 'Warli Village Scene',
    price: 850,
    description: 'Traditional Warli art depicting a village harvest celebration. Painted in white on earthy red background using bamboo stick.',
    status: 'in-stock',
    images: [
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'Jivya Soma Mashe',
      location: 'Palghar, Maharashtra',
      avatar: '',
    },
    category: 'Warli',
    rating: 4.7,
    relatedProducts: ['1', '4'],
  },
  {
    id: '3',
    name: 'Pattachitra Krishna Leela',
    price: 1800,
    description: 'Intricate Pattachitra scroll painting depicting Krishna Leela, crafted with natural colours and fine brush work on palm leaf.',
    status: 'in-stock',
    images: [
      'https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'Ananta Mahapatra',
      location: 'Raghurajpur, Odisha',
      avatar: '',
    },
    category: 'Pattachitra',
    rating: 4.8,
    relatedProducts: ['1', '5'],
  },
  {
    id: '4',
    name: 'Tanjore Goddess Lakshmi',
    price: 2000,
    description: 'Gold-foil Tanjore painting of Goddess Lakshmi with semi-precious stones and embossed relief work. A divine masterpiece.',
    status: 'in-stock',
    images: [
      'https://images.unsplash.com/photo-1582560475093-ba66accbc424?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'K. Rajan',
      location: 'Thanjavur, Tamil Nadu',
      avatar: '',
    },
    category: 'Tanjore',
    rating: 5.0,
    relatedProducts: ['3', '6'],
  },
  {
    id: '5',
    name: 'Kalamkari Peacock Panel',
    price: 650,
    description: 'Hand-drawn Kalamkari peacock on natural cotton fabric using vegetable dyes and a bamboo pen. Each stroke tells a story.',
    status: 'in-stock',
    images: [
      'https://images.unsplash.com/photo-1625631679491-29d2e3d49a1e?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'Padmaja Reddy',
      location: 'Srikalahasti, Andhra Pradesh',
      avatar: '',
    },
    category: 'Kalamkari',
    rating: 4.6,
    relatedProducts: ['2', '4'],
  },
  {
    id: '6',
    name: 'Warli Tree of Life',
    price: 700,
    description: 'Classic Warli Tree of Life motif painted in traditional style with geometric patterns surrounding the sacred tree.',
    status: 'low-stock',
    images: [
      'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'Balu Mashe',
      location: 'Palghar, Maharashtra',
      avatar: '',
    },
    category: 'Warli',
    rating: 4.5,
    relatedProducts: ['2', '5'],
  },
  {
    id: '7',
    name: 'Madhubani Radha Krishna',
    price: 1500,
    description: 'Exquisite Madhubani painting of Radha Krishna adorned with peacock feathers and lotus flowers, painted in vibrant hues.',
    status: 'in-stock',
    images: [
      'https://firebasestorage.googleapis.com/v0/b/ai-market-asst-1.firebasestorage.app/o/dataset%2Fmadhubani%2Fmadhubani0.jpg?alt=media&token=770c03a1-9df2-43a8-a9c7-addb89ca132a',
    ],
    artisan: {
      name: 'Kamla Devi',
      location: 'Darbhanga, Bihar',
      avatar: '',
    },
    category: 'Madhubani',
    rating: 4.9,
    relatedProducts: ['1', '3'],
  },
  {
    id: '8',
    name: 'Pattachitra Dashavatara',
    price: 950,
    description: 'Ten avatars of Lord Vishnu depicted in traditional Pattachitra style on cloth canvas with natural stone colours.',
    status: 'in-stock',
    images: [
      'https://images.unsplash.com/photo-1544892838-7d67fcf98a25?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'Suresh Maharana',
      location: 'Puri, Odisha',
      avatar: '',
    },
    category: 'Pattachitra',
    rating: 4.7,
    relatedProducts: ['3', '7'],
  },
  {
    id: '9',
    name: 'Kalamkari Mahabharata Scene',
    price: 1100,
    description: 'A detailed Kalamkari narrative panel from the Mahabharata, hand-drawn with a bamboo pen and vegetable dyes on cotton.',
    status: 'out-of-stock',
    images: [
      'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'Venkat Rao',
      location: 'Machilipatnam, Andhra Pradesh',
      avatar: '',
    },
    category: 'Kalamkari',
    rating: 4.8,
    relatedProducts: ['5', '4'],
  },
  {
    id: '10',
    name: 'Tanjore Ganesha',
    price: 1750,
    description: 'Auspicious Tanjore Ganesha painting with gold-leaf inlay, jade-green emerald accents, and intricate bas-relief work.',
    status: 'in-stock',
    images: [
      'https://images.unsplash.com/photo-1616763355548-1b606f439f86?auto=format&fit=crop&w=1000&q=80',
    ],
    artisan: {
      name: 'P. Subramaniam',
      location: 'Thanjavur, Tamil Nadu',
      avatar: '',
    },
    category: 'Tanjore',
    rating: 4.9,
    relatedProducts: ['4', '7'],
  },
]
